### ISSUE TITLE
i found a button once and never saw it again.

### ISSUE THREAD

**Issue by usor-usor** [g0aty/SickoMenu#112]
so i was just using hacks like normal whhile playing with my friends but than i found a button called ban when i went to the player tab and clicked on my alt. than when i pressed the button my alt was banned:"(my alts name) got banned by (my name) and i wasnt the host and than i never found that button again can someone help me find that button again?

**Comment by NikoFromOneshot** [comment]
So was it in the menu or in-game?

If it was in-game:
It might have been a bug, don't know how your client would have authorization to ban someone since only the host can ban people, but it could be possible

If it was in the menu:
Usually, if you aren't the host, this option wouldn't show up, even if it did, executing it wouldn't work since only the host is authorized to do that, there is an "Attempt Ban" option, but that only makes other clients time out, it doesn't actually ban them.

So, what I'm assuming happened is...
1. You somehow were given host (Host left or some bug gave you host)
2. You didn't notice you had host somehow.
3. You attempted to ban your alt, it worked because you had proper authorization to do so.
4. You were disconnected and reconnected, removing your host status.
5. You didn't test anymore and just made an issue

Of course, I'm willing to believe there is just a bug that caused this to happen, so I'll still investigate it.

Thank you for your contribution
-Niko Oneshot

**Comment by usor-usor** [comment]
> So was it in the menu or in-game?
> 
> If it was in-game: It might have been a bug, don't know how your client would have authorization to ban someone since only the host can ban people, but it could be possible
> 
> If it was in the menu: Usually, if you aren't the host, this option wouldn't show up, even if it did, executing it wouldn't work since only the host is authorized to do that, there is an "Attempt Ban" option, but that only makes other clients time out, it doesn't actually ban them.
> 
> So, what I'm assuming happened is...
> 
> 1. You somehow were given host (Host left or some bug gave you host)
> 2. You didn't notice you had host somehow.
> 3. You attempted to ban your alt, it worked because you had proper authorization to do so.
> 4. You were disconnected and reconnected, removing your host status.
> 5. You didn't test anymore and just made an issue
> 
> Of course, I'm willing to believe there is just a bug that caused this to happen, so I'll still investigate it.
> 
> Thank you for your contribution -Niko Oneshot

thanks

**Comment by usor-usor** [comment]
> So was it in the menu or in-game?
> 
> If it was in-game: It might have been a bug, don't know how your client would have authorization to ban someone since only the host can ban people, but it could be possible
> 
> If it was in the menu: Usually, if you aren't the host, this option wouldn't show up, even if it did, executing it wouldn't work since only the host is authorized to do that, there is an "Attempt Ban" option, but that only makes other clients time out, it doesn't actually ban them.
> 
> So, what I'm assuming happened is...
> 
> 1. You somehow were given host (Host left or some bug gave you host)
> 2. You didn't notice you had host somehow.
> 3. You attempted to ban your alt, it worked because you had proper authorization to do so.
> 4. You were disconnected and reconnected, removing your host status.
> 5. You didn't test anymore and just made an issue
> 
> Of course, I'm willing to believe there is just a bug that caused this to happen, so I'll still investigate it.
> 
> Thank you for your contribution -Niko Oneshot

can u also try to answer my other question under this one

**Comment by g0aty** [comment]
Coincidence.
